import { useEffect, useMemo, useState } from 'react'
import { Bot } from 'lucide-react'

const SECTIONS = [
  { id: 'overview', label: 'Overview' },
  { id: 'plot', label: 'Plot' },
  { id: 'cast', label: 'Cast' },
  { id: 'production', label: 'Production' },
  { id: 'development', label: 'Casting and Development' },
  { id: 'filming', label: 'Filming and Music' },
  { id: 'release', label: 'Release' },
  { id: 'reception', label: 'Reception and Box Office' },
  { id: 'legacy', label: 'Legacy' },
  { id: 'trivia', label: 'Trivia' },
  { id: 'crew', label: 'Crew' },
]

function paragraphFromTrivia(trivia) {
  if (!Array.isArray(trivia)) return ''
  return trivia.filter(Boolean).join(' ')
}

function P({ children }) {
  if (!children) return null
  return (
    <p
      style={{
        fontSize: 14,
        color: 'var(--text-2)',
        lineHeight: 1.85,
        margin: '0 0 10px 0',
      }}
    >
      {children}
    </p>
  )
}

function WikiSection({ id, title, children }) {
  return (
    <section id={`wiki-${id}`} style={{ marginBottom: 26, scrollMarginTop: 24 }}>
      {title ? (
        <h2
          style={{
            fontFamily: 'Bebas Neue',
            fontSize: 22,
            letterSpacing: '0.05em',
            color: 'var(--text)',
            margin: '0 0 10px 0',
            borderBottom: '1px solid var(--border)',
            paddingBottom: 6,
          }}
        >
          {title}
        </h2>
      ) : null}
      {children}
    </section>
  )
}

export default function WikiTab({ data, movie }) {
  const [activeId, setActiveId] = useState('overview')
  const triviaParagraph = useMemo(() => paragraphFromTrivia(data?.trivia), [data])

  useEffect(() => {
    const nodes = SECTIONS.map((s) => document.getElementById(`wiki-${s.id}`)).filter(Boolean)
    if (!nodes.length) return

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries.find((entry) => entry.isIntersecting)
        if (visible?.target?.id) {
          setActiveId(visible.target.id.replace('wiki-', ''))
        }
      },
      { rootMargin: '-80px 0px -60% 0px', threshold: 0 }
    )

    nodes.forEach((node) => observer.observe(node))
    return () => observer.disconnect()
  }, [data])

  const scrollTo = (id) => {
    document.getElementById(`wiki-${id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  if (!data || !movie) return null

  const production = data.production || {}
  const release = data.release || {}

  return (
    <div className="fade-in" style={{ display: 'flex', gap: 0, minHeight: 420 }}>
      <nav
        style={{
          width: 210,
          flexShrink: 0,
          position: 'sticky',
          top: 0,
          alignSelf: 'flex-start',
          paddingTop: 4,
          paddingRight: 20,
          borderRight: '1px solid var(--border)',
        }}
      >
        <p
          style={{
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
            color: 'var(--text-3)',
            margin: '0 0 8px 0',
            paddingBottom: 6,
            borderBottom: '1px solid var(--border)',
          }}
        >
          Contents
        </p>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          {SECTIONS.map((section) => {
            const isActive = section.id === activeId
            return (
              <a
                key={section.id}
                href={`#wiki-${section.id}`}
                onClick={(e) => {
                  e.preventDefault()
                  scrollTo(section.id)
                }}
                style={{
                  textDecoration: 'none',
                  color: isActive ? 'var(--amber)' : 'var(--text-3)',
                  fontSize: 12,
                  fontWeight: isActive ? 600 : 400,
                  lineHeight: 1.9,
                }}
              >
                {section.label}
              </a>
            )
          })}
        </div>
      </nav>

      <article style={{ flex: 1, minWidth: 0, paddingLeft: 30 }}>
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            padding: '4px 12px',
            borderRadius: 6,
            marginBottom: 16,
            background: 'rgba(212,168,83,0.08)',
            border: '1px solid rgba(212,168,83,0.18)',
            fontSize: 11,
            fontWeight: 600,
            color: 'var(--amber)',
          }}
        >
          <Bot size={12} />
          Generated by AI
        </div>

        <h1
          style={{
            fontFamily: 'Bebas Neue',
            fontSize: 36,
            letterSpacing: '0.03em',
            color: 'var(--text)',
            lineHeight: 1,
            margin: '0 0 4px 0',
            borderBottom: '1px solid var(--border)',
            paddingBottom: 12,
          }}
        >
          {movie.title}
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-3)', margin: '0 0 26px 0' }}>
          {movie.year} film
        </p>

        <WikiSection id="overview" title="Overview">
          <P>{data.overview}</P>
        </WikiSection>

        <WikiSection id="plot" title="Plot">
          <P>{data.plot}</P>
        </WikiSection>

        {Array.isArray(data.cast_table) && data.cast_table.length > 0 ? (
          <WikiSection id="cast" title="Cast">
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr>
                  <th style={thStyle}>Actor</th>
                  <th style={thStyle}>Role</th>
                  <th style={thStyle}>Notes</th>
                </tr>
              </thead>
              <tbody>
                {data.cast_table.map((cast, idx) => (
                  <tr key={`${cast.actor || 'cast'}-${idx}`}>
                    <td style={{ ...tdStyle, color: 'var(--text)', fontWeight: 600 }}>{cast.actor}</td>
                    <td style={tdStyle}>{cast.role}</td>
                    <td style={tdStyle}>{cast.notes}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </WikiSection>
        ) : null}

        <WikiSection id="production" title="Production">
          <P>{production.development}</P>
        </WikiSection>

        <WikiSection id="development" title="Casting and Development">
          <P>{production.casting}</P>
        </WikiSection>

        <WikiSection id="filming" title="Filming and Music">
          <P>{production.filming}</P>
          <P>{production.music}</P>
        </WikiSection>

        <WikiSection id="release" title="Release">
          <P>{release.theatrical}</P>
        </WikiSection>

        <WikiSection id="reception" title="Reception and Box Office">
          <P>{release.reception}</P>
          <P>{release.box_office}</P>
        </WikiSection>

        <WikiSection id="legacy" title="Legacy">
          <P>{data.legacy}</P>
        </WikiSection>

        <WikiSection id="trivia" title="Trivia">
          <P>{triviaParagraph}</P>
        </WikiSection>

        {Array.isArray(data.crew) && data.crew.length > 0 ? (
          <WikiSection id="crew" title="Crew">
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr>
                  <th style={thStyle}>Name</th>
                  <th style={thStyle}>Role</th>
                </tr>
              </thead>
              <tbody>
                {data.crew.map((member, idx) => (
                  <tr key={`${member.name || 'crew'}-${idx}`}>
                    <td style={{ ...tdStyle, color: 'var(--text)', fontWeight: 600 }}>{member.name}</td>
                    <td style={tdStyle}>{member.role}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </WikiSection>
        ) : null}
      </article>
    </div>
  )
}

const thStyle = {
  textAlign: 'left',
  padding: '8px 12px',
  fontSize: 11,
  fontWeight: 700,
  letterSpacing: '0.06em',
  textTransform: 'uppercase',
  color: 'var(--text-3)',
  borderBottom: '1px solid var(--border)',
  background: 'var(--surface)',
}

const tdStyle = {
  padding: '10px 12px',
  color: 'var(--text-2)',
  borderBottom: '1px solid var(--border)',
  verticalAlign: 'top',
  lineHeight: 1.6,
}
